/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "himfpihqqwfotfzfxbfs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbWZwaWhxcXdmb3RmemZ4YmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTc0MDQsImV4cCI6MjA2ODg3MzQwNH0.dPWB-dtX1J-hlCWpL4d90gg4_ZKvTGca3Xe8pmEqTp8"